import { Language } from "./types";

type SiteConfig = {
  name: string;
  description: Record<Language, string>;
  contact: {
    whatsapp?: string;
    email: string;
    discord: string;
  };
  texts: Record<string, Record<Language, string>>;
  underConstruction?: boolean;
};

export const siteConfig: SiteConfig = {
  underConstruction: false,
  name: "PixelHub Host",
  description: {
    en: "Premium Minecraft Server Hosting",
    pt: "Hospedagem Premium de Servidores Minecraft",
    de: "Premium Minecraft Server Hosting",
    fr: "Hébergement Premium de Serveurs Minecraft",
  },
  contact: {
    discord: "https://discord.gg/mquaVhs5sr",
    whatsapp: "https://wa.me/5516993981473",
    email: "",
  },
  texts: {
    heroTitle: {
      en: "Premium Minecraft Server Hosting",
      pt: "Hospedagem Premium de Servidores Minecraft",
      de: "Premium Minecraft Server Hosting",
      fr: "Hébergement Premium de Serveurs Minecraft",
    },
    heroSubtitle: {
      en: "High Performance, DDoS protection, and reliable Support for your Minecraft Server",
      pt: "Alto desempenho, proteção DDoS e suporte confiável para seu Servidor Minecraft",
      de: "Hohe Leistung, DDoS-Schutz und zuverlässiger Support für Ihren Minecraft-Server",
      fr: "Haute performance, protection DDoS et support fiable pour votre Serveur Minecraft",
    },
    features: {
      en: "Features",
      pt: "Recursos",
      de: "Funktionen",
      fr: "Fonctionnalités",
    },
    pricing: {
      en: "Pricing",
      pt: "Preços",
      de: "Preise",
      fr: "Tarifs",
    },
    contact: {
      en: "Contact",
      pt: "Contato",
      de: "Kontakt",
      fr: "Contact",
    },
    getStarted: {
      en: "Get Started",
      pt: "Começar Agora",
      de: "Jetzt Starten",
      fr: "Commencer",
    },
    learnMore: {
      en: "Learn More",
      pt: "Saiba Mais",
      de: "Mehr Erfahren",
      fr: "En Savoir Plus",
    },
    contactTitle: {
      en: "Get in Touch",
      pt: "Entre em Contato",
      de: "Kontaktieren Sie Uns",
      fr: "Contactez-Nous",
    },
    contactSubtitle: {
      en: "Have questions? We're here to help!",
      pt: "Tem perguntas? Estamos aqui para ajudar!",
      de: "Haben Sie Fragen? Wir sind hier um zu helfen!",
      fr: "Des questions? Nous sommes là pour vous aider!",
    },
    popularPlan: {
      en: "Most Popular",
      pt: "Mais Popular",
      de: "Am beliebtesten",
      fr: "Plus Populaire",
    },
    selectPlan: {
      en: "Select Plan",
      pt: "Selecionar Plano",
      de: "Plan Auswählen",
      fr: "Sélectionner le Plan",
    },
    featuresTitle: {
      en: "Premium Features",
      pt: "Recursos Premium",
      de: "Premium Funktionen",
      fr: "Fonctionnalités Premium",
    },
    featuresSubtitle: {
      en: "Experience the best in Minecraft server hosting",
      pt: "Experimente o melhor em hospedagem de servidores Minecraft",
      de: "Erleben Sie das Beste in Minecraft-Server-Hosting",
      fr: "Découvrez le meilleur de l'hébergement de serveurs Minecraft",
    },
    ddosProtectionDesc: {
      en: "Basic protection against DDoS attacks",
      pt: "Proteção básica contra ataques DDoS",
      de: "Grundlegender Schutz gegen DDoS-Angriffe",
      fr: "Protection de base contre les attaques DDoS",
    },
    xeonCpuDesc: {
      en: "High-performance processors",
      pt: "Processadores de alto desempenho",
      de: "Hochleistungsprozessoren",
      fr: "Processeurs haute performance",
    },
    networkSpeedDesc: {
      en: "Ultra-fast connectivity for minimal latency",
      pt: "Conectividade ultra-rápida para latência mínima",
      de: "Ultraschnelle Verbindung für minimale Latenz",
      fr: "Connectivité ultra-rapide pour une latence minimale",
    },
    pricingTitle: {
      en: "Choose Your Plan",
      pt: "Escolha Seu Plano",
      de: "Wählen Sie Ihren Plan",
      fr: "Choisissez Votre Plan",
    },
    pricingSubtitle: {
      en: "Find the perfect plan for your Minecraft server",
      pt: "Encontre o plano perfeito para seu servidor Minecraft",
      de: "Finden Sie den perfekten Plan für Ihren Minecraft-Server",
      fr: "Trouvez le plan parfait pour votre serveur Minecraft",
    },
    footerText: {
      en: "© 2025 PixelHub Host. All rights reserved.",
      pt: "© 2025 PixelHub Host. Todos os direitos reservados.",
      de: "© 2025 PixelHub Host. Alle Rechte vorbehalten.",
      fr: "© 2025 PixelHub Host. Tous droits réservés.",
    },
    cpuThreads: {
      en: "✅vCores",
      pt: "✅vCores",
      de: "✅vCores",
      fr: "✅vCores",
    },
    ram: {
      en: "✅RAM DDR4",
      pt: "✅RAM DDR4",
      de: "✅RAM DDR4",
      fr: "✅RAM DDR4",
    },
    storage: {
      en: "✅NVMe",
      pt: "✅NVMe",
      de: "✅NVMe",
      fr: "✅NVMe",
    },
    backups: {
      en: "✅Backups",
      pt: "✅Backups",
      de: "✅Backups",
      fr: "✅Sauvegardes",
    },
    databases: {
      en: "✅Databases",
      pt: "✅Bancos de Dados",
      de: "✅Datenbanken",
      fr: "✅Bases de données",
    },
    ports: {
      en: "✅Ports",
      pt: "✅Portas",
      de: "✅Ports",
      fr: "✅Ports",
    },
    month: {
      en: "month",
      pt: "mês",
      de: "Monat",
      fr: "mois",
    },
    custom: {
      en: "Custom",
      pt: "Personalizado",
      de: "Individuell",
      fr: "Personnalisé",
    },
    contactUs: {
      en: "Contact us",
      pt: "Entre em contato",
      de: "Kontaktieren Sie uns",
      fr: "Contactez-nous",
    },
    soldOut: {
      en: "SOLD OUT",
      pt: "ESGOTADO",
      de: "AUSVERKAUFT",
      fr: "ÉPUISÉ",
    },
    from: {
      en: "from",
      pt: "a partir de",
      de: "ab",
      fr: "à partir de",
    },
    testServer: {
      en: "Test Server",
      pt: "Servidor de Teste",
      de: "Testserver",
      fr: "Serveur de Test",
    },
    testServerDesc: {
      en: "Try our server performance with this free test server",
      pt: "Experimente nosso desempenho com este servidor de teste gratuito",
      de: "Testen Sie unsere Serverleistung mit diesem kostenlosen Testserver",
      fr: "Essayez notre performance avec ce serveur de test gratuit",
    },
    domain: {
      en: "Domain",
      pt: "Domínio",
      de: "Domain",
      fr: "Domaine",
    },
    bedrockPort: {
      en: "Bedrock Port",
      pt: "Porta Bedrock",
      de: "Bedrock Port",
      fr: "Port Bedrock",
    },
    cpu: {
      en: "CPU",
      pt: "CPU",
      de: "CPU",
      fr: "CPU",
    },
    memory: {
      en: "Memory",
      pt: "Memória",
      de: "Arbeitsspeicher",
      fr: "Mémoire",
    },
    checking: {
      en: "Checking...",
      pt: "Verificando...",
      de: "Überprüfung...",
      fr: "Vérification...",
    },
    serverOffline: {
      en: "Server Offline",
      pt: "Servidor Offline",
      de: "Server Offline",
      fr: "Serveur Hors Ligne",
    },
    connectToTestServer: {
      en: "Connect to Test Server",
      pt: "Conectar ao Servidor de Teste",
      de: "Mit Testserver verbinden",
      fr: "Se Connecter au Serveur de Test",
    },
    customDomain: {
      en: "Custom Domain",
      pt: "Domínio Personalizado",
      de: "Eigene Domain",
      fr: "Domaine personnalisé",
    },
    freeSubdomainDesc: {
      en: "Get a FREE .pixelhubhost.com subdomain",
      pt: "Subdomínio .pixelhubhost.com GRÁTIS",
      de: "Erhalten Sie eine kostenlose .pixelhubhost.com Subdomain",
      fr: "Obtenez un sous-domaine .pixelhubhost.com gratuit",
    },
    reliableSupportDesc: {
      en: "Professional assistance whenever you need it",
      pt: "Assistência profissional sempre que precisar",
      de: "Professionelle Unterstützung wann immer Sie sie brauchen",
      fr: "Assistance professionnelle quand vous en avez besoin",
    },
    dailyBackupsDesc: {
      en: "Automated daily backups of your server",
      pt: "Backups automáticos diários do seu servidor",
      de: "Automatische tägliche Backups Ihres Servers",
      fr: "Sauvegardes quotidiennes automatiques de votre serveur",
    },
    customDomainDesc: {
      en: "Your custom domain description here",
      pt: "Descrição do seu domínio personalizado aqui",
      de: "Beschreibung Ihrer benutzerdefinierten Domain hier",
      fr: "Description de votre domaine personnalisé ici",
    },
    extraPort: {
      en: "Extra Port",
      pt: "Porta Extra",
      de: "Zusätzlicher Port",
      fr: "Port supplémentaire",
    },
    extraPortDesc: {
      en: "Add an additional port to your server.",
      pt: "Adicione uma porta extra ao seu servidor.",
      de: "Fügen Sie Ihrem Server einen zusätzlichen Port hinzu.",
      fr: "Ajoutez un port supplémentaire à votre serveur.",
    },
    extraBackup: {
      en: "Extra Backup",
      pt: "Backup Extra",
      de: "Zusätzliches Backup",
      fr: "Sauvegarde supplémentaire",
    },
    extraBackupDesc: {
      en: "Purchase additional backup slots for your server.",
      pt: "Compre slots de backup adicionais para seu servidor.",
      de: "Kaufen Sie zusätzliche Backup-Slots für Ihren Server.",
      fr: "Achetez des emplacements de sauvegarde supplémentaires pour votre serveur.",
    },
    extraDatabase: {
      en: "Extra Database",
      pt: "Banco de Dados Extra",
      de: "Zusätzliche Datenbank",
      fr: "Base de données supplémentaire",
    },
    extraDatabaseDesc: {
      en: "Add more databases to your server.",
      pt: "Adicione mais bancos de dados ao seu servidor.",
      de: "Fügen Sie Ihrem Server weitere Datenbanken hinzu.",
      fr: "Ajoutez plus de bases de données à votre serveur.",
    },
    systemStatus: {
      en: "System Status",
      pt: "Status do Sistema",
      de: "Systemstatus",
      fr: "Statut du Système",
    },
    footerDescription: {
      en: "PixelHub Host provides premium Minecraft server hosting with top performance, security, and support.",
      pt: "A PixelHub Host oferece hospedagem premium de servidores Minecraft com desempenho, segurança e suporte de alto nível.",
      de: "PixelHub Host bietet Premium-Minecraft-Server-Hosting mit bester Leistung, Sicherheit und Support.",
      fr: "PixelHub Host propose un hébergement premium de serveurs Minecraft avec performance, sécurité et support de premier ordre.",
    },
    aboutUs: {
      en: "About Us",
      pt: "Sobre Nós",
      de: "Über Uns",
      fr: "À Propos",
    },
    company: {
      en: "Company",
      pt: "Empresa",
      de: "Unternehmen",
      fr: "Entreprise",
    },
    services: {
      en: "Services",
      pt: "Serviços",
      de: "Dienstleistungen",
      fr: "Services",
    },
    support: {
      en: "Support",
      pt: "Suporte",
      de: "Support",
      fr: "Support",
    },
    helpCenter: {
      en: "Help Center",
      pt: "Central de Ajuda",
      de: "Hilfezentrum",
      fr: "Centre d'aide",
    },
    documentation: {
      en: "Documentation",
      pt: "Documentação",
      de: "Dokumentation",
      fr: "Documentation",
    },
    serverTypes: {
      en: "Server Types",
      pt: "Tipos de Servidor",
      de: "Servertypen",
      fr: "Types de Serveur",
    },
    modpackHosting: {
      en: "Modpack Hosting",
      pt: "Hospedagem de Modpack",
      de: "Modpack-Hosting",
      fr: "Hébergement de Modpack",
    },
    pluginInstallation: {
      en: "Plugin Installation",
      pt: "Instalação de Plugins",
      de: "Plugin-Installation",
      fr: "Installation de Plugins",
    },
    serverManagement: {
      en: "Server Management",
      pt: "Gerenciamento de Servidor",
      de: "Serververwaltung",
      fr: "Gestion de Serveur",
    },
    footerCopyright: {
      en: "© 2025 PixelHub Host. All rights reserved.",
      pt: "© 2025 PixelHub Host. Todos os direitos reservados.",
      de: "© 2025 PixelHub Host. Alle Rechte vorbehalten.",
      fr: "© 2025 PixelHub Host. Tous droits réservés.",
    },
    privacyPolicy: {
      en: "Privacy Policy",
      pt: "Política de Privacidade",
      de: "Datenschutzrichtlinie",
      fr: "Politique de Confidentialité",
    },
    termsOfService: {
      en: "Terms of Service",
      pt: "Termos de Serviço",
      de: "Nutzungsbedingungen",
      fr: "Conditions d'utilisation",
    },
    sitemap: {
      en: "Sitemap",
      pt: "Mapa do Site",
      de: "Seitenverzeichnis",
      fr: "Plan du site",
    },
    legal: {
      en: "Legal",
      pt: "Legal",
      de: "Rechtliches",
      fr: "Mentions légales",
    },
    addons: {
      en: "Addons",
      pt: "Complementos",
      de: "Erweiterungen",
      fr: "Modules complémentaires",
    },
    addonsSubtitle: {
      en: "Enhance your server with these optional features",
      pt: "Aprimore seu servidor com estes recursos opcionais",
      de: "Erweitern Sie Ihren Server mit diesen optionalen Funktionen",
      fr: "Améliorez votre serveur avec ces fonctionnalités optionnelles",
    },
    mcHosting: {
      en: "Minecraft Hosting",
      pt: "Hospedagem Minecraft",
      de: "Minecraft Hosting",
      fr: "Hébergement Minecraft",
    },
    aboutUsTitle: {
      en: "About Us",
      pt: "Sobre Nós",
      de: "Über Uns",
      fr: "À Propos",
    },
    aboutUsIntro: {
      en: "PixelHub Host is dedicated to providing premium Minecraft server hosting with top performance, security, and support.",
      pt: "A PixelHub Host é dedicada a fornecer hospedagem premium de servidores Minecraft com desempenho, segurança e suporte de alto nível.",
      de: "PixelHub Host bietet Premium-Minecraft-Server-Hosting mit bester Leistung, Sicherheit und Support.",
      fr: "PixelHub Host propose un hébergement premium de serveurs Minecraft avec performance, sécurité et support de premier ordre.",
    },
    aboutUsMission: {
      en: "Our mission is to empower gamers and communities with reliable, high-performance servers and professional assistance.",
      pt: "Nossa missão é capacitar jogadores e comunidades com servidores confiáveis, de alto desempenho e assistência profissional.",
      de: "Unsere Mission ist es, Spielern und Communities zuverlässige, leistungsstarke Server und professionelle Unterstützung zu bieten.",
      fr: "Notre mission est d'offrir aux joueurs et aux communautés des serveurs fiables, performants et une assistance professionnelle.",
    },
    aboutUsValues1: {
      en: "Performance-first infrastructure",
      pt: "Infraestrutura focada em desempenho",
      de: "Performance-orientierte Infrastruktur",
      fr: "Infrastructure axée sur la performance",
    },
    aboutUsValues2: {
      en: "24/7 expert support",
      pt: "Suporte especializado 24/7",
      de: "24/7 Experten-Support",
      fr: "Support expert 24/7",
    },
    aboutUsValues3: {
      en: "Affordable and transparent pricing",
      pt: "Preços acessíveis e transparentes",
      de: "Erschwingliche und transparente Preise",
      fr: "Tarification abordable et transparente",
    },
    aboutUsValues4: {
      en: "Continuous innovation",
      pt: "Inovação contínua",
      de: "Ständige Innovation",
      fr: "Innovation continue",
    },
    aboutUsValues5: {
      en: "Community-driven service",
      pt: "Serviço orientado à comunidade",
      de: "Community-orientierter Service",
      fr: "Service axé sur la communauté",
    },
    aboutUsTeam: {
      en: "Our team is made up of passionate gamers, developers, and support specialists who understand what you need for a great Minecraft experience.",
      pt: "Nossa equipe é formada por gamers, desenvolvedores e especialistas em suporte apaixonados que entendem o que você precisa para uma ótima experiência Minecraft.",
      de: "Unser Team besteht aus leidenschaftlichen Gamern, Entwicklern und Support-Spezialisten, die wissen, was für ein großartiges Minecraft-Erlebnis nötig ist.",
      fr: "Notre équipe est composée de joueurs passionnés, de développeurs et de spécialistes du support qui comprennent vos besoins pour une expérience Minecraft optimale.",
    },
    aboutUsContact: {
      en: "Want to know more? Reach out to us anytime!",
      pt: "Quer saber mais? Fale conosco a qualquer momento!",
      de: "Möchten Sie mehr erfahren? Kontaktieren Sie uns jederzeit!",
      fr: "Vous voulez en savoir plus ? Contactez-nous à tout moment !",
    },
  },
};
